[package]
name = "bench-keccak256"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

sha3 = { version = "0.10.8" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
sha3-asm = { path = "../sha3-asm", package = "sha3" }
keccak-asm = { path = "../keccak-asm" }

[dev-dependencies]
criterion = "0.5.1"
hex = "0.4.3"

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
codegen-units = 1

debug = 2
strip = false

[[bench]]
name = "bench"
harness = false
