[package]
name = "bench-keccak256"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
rand = "0.8.5"

sha3 = { version = "0.10.8", optional = true }
tiny-keccak = { version = "2.0.2", optional = true, features = ["keccak"] }

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
codegen-units = 1

debug = 2
strip = false
